sonar.projectKey=bluebird-works_rpi5-recorder
sonar.projectName=rpi5-recorder
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/vendor/**,**/dist/**,**/build/**,**/*.min.js,**/venv/**,**/.venv/**,**/__pycache__/**
sonar.javascript.node.maxspace=2048
